# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 18:12
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_assignee_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
    ]
